# Generated by Django 4.1.4 on 2022-12-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='CounterPartMinistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'counterpart_ministry',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
        migrations.CreateModel(
            name='ExecutingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'executing_agency',
            },
        ),
        migrations.CreateModel(
            name='ImplementingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'implementing_partner',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('code', models.PositiveIntegerField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DEFINED', 'Defined'), ('ON-GOING', 'On Going'), ('COMPLETED', 'Completed')], default='DEFINED', max_length=50)),
                ('assistance_code_type', models.IntegerField()),
                ('budget_type', models.CharField(choices=[('Off Budget', 'Off Budget'), ('On Budget', 'On Budget')], max_length=10, null=True)),
                ('humanitarian', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('commitments', models.PositiveBigIntegerField()),
                ('agreement_date', models.DateField()),
                ('date_of_effectiveness', models.DateField()),
                ('counterpart_ministry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.counterpartministry')),
                ('donor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.donor')),
                ('executing_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.executingagency')),
                ('project_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.address')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.sector')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
