version: "3.8"

services:

  # Database Postgres
  db:
    image: postgres
    restart: always
    container_name: pgsql_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  # Django App
  web:
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    container_name: project-summarizer-service
    image: "project-summarizer-service"
    restart: always
    depends_on:
      - db

volumes:
  pg-data:
    driver: local